### ISSUE TITLE
FutureWarning for using `torch.load` with (implicit) `weights_only=False`

### ISSUE THREAD

**Issue by Skgland** [ultralytics/ultralytics#14994]
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

```
/home/user/.local/lib/python3.9/site-packages/ultralytics/nn/tasks.py:714: 
FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. 
It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). 
In a future release, the default value for `weights_only` will be flipped to `True`. 
This limits the functions that could be executed during unpickling. 
Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. 
We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. 
Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(file, map_location="cpu")

```

Note: added linebreakes for readability

### Environment

```sh
$> python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ultralytics
>>> ultralytics.checks()
Ultralytics YOLOv8.1.24 🚀 Python-3.9.2 torch-2.4.0 CPU (Cortex-A55)
Setup complete ✅ (8 CPUs, 15.6 GB RAM, 24.2/116.9 GB disk)
```

### Minimal Reproducible Example

```python3
from ultralytics import YOLO

model = "./some_obb_model_file"
YOLO(model, task='obb')
```

Any model and task appear to cause the issue.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Skgland** [comment]
This FutureWarning appears to be new in torch 2.4.0 as using a different environment with torch 2.3.0 did not reproduce the warning, but updating torch 2.4.0 caused it to appear.

**Comment by pderrenger** [comment]
@Skgland thank you for bringing this to our attention. The FutureWarning you're encountering is indeed related to changes in PyTorch 2.4.0. To address this, please ensure you are using the latest version of the Ultralytics package, as updates may include fixes for compatibility with newer PyTorch versions. If the issue persists, setting `weights_only=True` when loading models can mitigate the warning. We appreciate your understanding and patience as we work to maintain compatibility with evolving dependencies.

**Comment by glenn-jocher** [comment]
@Skgland fixed in the latest versions of `ultralytics`, please upgrade with `pip install -U ultralytics`

**Comment by finch2019** [comment]
I have upgrade with `pip install -U ultralytics` , but the bug still exists.

    /root/flourish/yolov9/models/experimental.py:243: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). 
    In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. 
    We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
    ckpt = torch.load(attempt_download(w), map_location='cpu')  # load

**Comment by Skgland** [comment]
Running

```python
# mvp.py
from ultralytics import YOLO, checks

checks()

print("Pre Model Loading")
model = "./model.py"
YOLO(model, task='obb')
print("Post Model Loading")
```

after updating ultralytics I now get 

```sh
$> python ./mvp.py
python .\mvp.py
Ultralytics YOLOv8.2.74 🚀 Python-3.11.9 torch-2.4.0+cpu CPU (Intel Core(TM) i5-10400 2.90GHz)
Setup complete ✅ (12 CPUs, 15.8 GB RAM, 1217.3/1863.0 GB disk)
Pre Model Loading
Post Model Loading
```

so this looks indeed fixed in the new version.

**Comment by Skgland** [comment]
@finch2019 I don't see anything pointing to ultralytics in your warning message

**Comment by finch2019** [comment]
> @finch2019 I don't see anything pointing to ultralytics in your warning message

ohh，sorry，let me check again.

**Comment by Skgland** [comment]
Based on the warning you shared it looks like it originates in [yolov9](https://github.com/WongKinYiu/yolov9) to be more precise [here](https://github.com/WongKinYiu/yolov9/blob/main/models/experimental.py#L243)

**Comment by pderrenger** [comment]
It appears the warning you're encountering originates from the YOLOv9 repository, specifically in the `experimental.py` file. This is not related to the Ultralytics YOLO repository. Please check the YOLOv9 repository for updates or consider raising the issue there. If you have any further questions related to Ultralytics YOLO, feel free to ask.

**Comment by swgu98** [comment]
I think it's not Ultralytics' problem. I haven't used it but it also generates this warning. It seems to be just a security warning. I don't know if the return value will also be different. Have you solved it?

**Comment by glenn-jocher** [comment]
It seems the warning is related to PyTorch's handling of `torch.load`. If you're using the latest version of Ultralytics and still see this, it might be a general PyTorch issue. Ensure your environment is up to date.

**Comment by Meehai** [comment]
just in case anyone wants a quick fix that doesn't solve the underlying issue with the unsafeness of pickle and loading arbitrary models:

```python
import warnings
warnings.filterwarnings("ignore", "You are using `torch.load` with `weights_only=False`*.")
```

**Comment by glenn-jocher** [comment]
Thank you for sharing the workaround. While it suppresses the warning, it's important to remain cautious with untrusted models.

**Comment by gary1592** [comment]
> @Skgland fixed in the latest versions of `ultralytics`, please upgrade with `pip install -U ultralytics`

@glenn-jocher Thanks for you advice,I have resolved the annoying problem.

**Comment by glenn-jocher** [comment]
I'm glad to hear the issue is resolved! If you have any more questions or need further assistance, feel free to reach out to the Ultralytics community.
