### ISSUE TITLE
Yolo pose , mistake in labels caching.

### ISSUE THREAD

**Issue by PallottaEnrico** [ultralytics/ultralytics#1578]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug
@glenn-jocher 
In the function [cache_labels](https://github.com/ultralytics/ultralytics/blob/pose/ultralytics/yolo/data/dataset.py) line 80, the number of corrupt labels is initialized with the number of classes:
`nc = len(self.data['names'])`

This leads the label scanning to always find at least one corrupt label.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@PallottaEnrico yes you are right! I am able to reproduce this. I'll push a fix in Pose branch.

**Comment by glenn-jocher** [comment]
@PallottaEnrico fixed in https://github.com/ultralytics/ultralytics/pull/1347/commits/da6c9a1da88ef81600fe09cf0484907ed56c489b

**Comment by PallottaEnrico** [comment]
@glenn-jocher the problem is still there.
It always starts counting the corrupted images from 1 and not from 0.
I think that removing line 80 should fix it.

**Comment by glenn-jocher** [comment]
@PallottaEnrico, thank you for your feedback. I apologize for any inconvenience that this issue made. I understand that after my previous attempt to fix the issue the problem persisted. Indeed, the suggested solution of removing line 80 should work since it would stop setting the value of `nc` to be equal to the length of `self.data['names']`. Again, thank you for your feedback as it helps us improve YOLOv8. Please let me know if you have any other questions or concerns.
