### ISSUE TITLE
module 'torch.mps' has no attribute 'get_mem_info'

### ISSUE THREAD

**Issue by HerbOtto** [ultralytics/ultralytics#19683]
### Search before asking

- [x] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

Since v8.3.86 I'm now seeing the error:

**.../python3.11/site-packages/ultralytics/engine/trainer.py", line 495, in _get_memory
    total = torch.mps.get_mem_info()[0]
            ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'torch.mps' has no attribute 'get_mem_info'**

I'm running on a M4 with 64gig RAM and utilize only half the RAM during training. This is a long-term project that stopped training until I rolled back to 8.3.85 which does not generate the error. Using the yolo11n model.

### Environment

Ultralytics 8.3.89 🚀 Python-3.11.11 torch-2.6.0 CPU (Apple M4 Pro)
Setup complete ✅ (12 CPUs, 64.0 GB RAM, 409.5/926.4 GB disk)

OS                  macOS-15.3.2-arm64-arm-64bit
Environment         Darwin
Python              3.11.11
Install             pip
Path                ~/miniconda3/envs/coral/lib/python3.11/site-packages/ultralytics
RAM                 64.00 GB
Disk                409.5/926.4 GB
CPU                 Apple M4 Pro
CPU count           12
GPU                 None
GPU count           None
CUDA                None

numpy               ✅ 1.26.4<=2.1.1,>=1.23.0
matplotlib          ✅ 3.10.1>=3.3.0
opencv-python       ✅ 4.11.0.86>=4.6.0
pillow              ✅ 11.1.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.15.2>=1.4.1
torch               ✅ 2.6.0>=1.8.0
torch               ✅ 2.6.0!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.21.0>=0.9.0
tqdm                ✅ 4.67.1>=4.64.0
psutil              ✅ 7.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.14>=2.0.0

### Minimal Reproducible Example

`results = model.train(...)`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by UltralyticsAssistant** [comment]
👋 Hello @HerbOtto, thank you for reporting this issue and for using Ultralytics 🚀! We appreciate your detailed description and environment information—it’s very helpful for debugging.

If this is a 🐛 Bug Report, please ensure you’ve provided a [minimum reproducible example (MRE)](https://docs.ultralytics.com/help/minimum-reproducible-example/) to help us pinpoint the issue. From your description, it seems you’ve already included relevant details, which is great! If possible, please also share a complete code snippet or additional steps to reproduce the error.

In the meantime, we recommend the following steps:
1. Upgrade to the latest `ultralytics` package to ensure the issue hasn’t been resolved in a more recent update:
   ```bash
   pip install -U ultralytics
   ```
2. Verify your environment meets all [requirements](https://github.com/ultralytics/ultralytics/blob/main/pyproject.toml) and is running on a supported configuration.

If the issue persists, an Ultralytics engineer will review your report and assist you shortly. You can also try running YOLO in one of the verified environments below to check if the issue is specific to your setup:

- **Notebooks** with free GPU: <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"/></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolo11"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

For additional support, feel free to join the Ultralytics community:
- Chat in real-time on [Discord](https://discord.com/invite/ultralytics) 🎧
- Participate in deeper discussions on [Discourse](https://community.ultralytics.com/)
- Share knowledge or ask for advice on our [Subreddit](https://reddit.com/r/Ultralytics)

We’ll work together to resolve this issue as quickly as possible. Thank you for your patience and understanding! ✨

**Comment by glenn-jocher** [comment]
@HerbOtto thank you for reporting this issue and providing detailed environment information. This is a known compatibility error that's been resolved in our latest releases. To fix it:

1. Update to the newest Ultralytics version:  
`pip install -U ultralytics`

The fix adds proper checks for PyTorch MPS memory methods availability. Let us know if you still encounter any issues after updating.

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has been merged in [PR #19686](https://github.com/ultralytics/ultralytics/pull/19686). 🎉  

### Key Changes  
The PR updates the memory usage calculation for MPS devices to improve accuracy and reliability. Specifically:  
- The memory fraction calculation now uses `psutil.virtual_memory().percent` instead of `torch.mps.get_mem_info()`.  
- This update enhances memory usage reporting for MPS devices like those on Apple hardware, improving compatibility, performance, and user experience when running YOLO models.  

Credit goes to @Y-T-G for authoring the PR, with contributions from @glenn-jocher and @iCMDdev. 🙌  

### How to Test  
You can test the latest changes by running:  
```bash
pip install git+https://github.com/ultralytics/ultralytics.git@main
```  
Alternatively, you can wait for the next official PyPI release to see if the issue is resolved.  

### Feedback Request  
Let us know if the changes resolve your issue. If the problem persists, feel free to provide further details so we can assist.  

Thank you for reporting this and helping improve Ultralytics! 🙏 Your feedback is invaluable.

**Comment by HerbOtto** [comment]
version 90 did not fix the issue, below is the full trace...

**Traceback (most recent call last):
  File "/Users/otto/develop/neural/yolo-coral/train.py", line 570, in <module>
    results = model.train(
              ^^^^^^^^^^^^
  File "/Users/otto/miniconda3/envs/coral/lib/python3.11/site-packages/ultralytics/engine/model.py", line 810, in train
    This method supports two modes of hyperparameter tuning: using Ray Tune or a custom tuning method.
    ^^^^^^^^^^^^^^^^^^^^
  File "/Users/otto/miniconda3/envs/coral/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 208, in train
    ddp_cleanup(self, str(file))
^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/otto/miniconda3/envs/coral/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 455, in _do_train
    self.scheduler.last_epoch = self.epoch  # do not move
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/otto/miniconda3/envs/coral/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 495, in _get_memory
    if self.device.type == "mps":
                    ^^^^^^^^^^^^^^
AttributeError: module 'torch.mps' has no attribute 'get_mem_info'**


Ultralytics 8.3.90 🚀 Python-3.11.11 torch-2.6.0 CPU (Apple M4 Pro)
Setup complete ✅ (12 CPUs, 64.0 GB RAM, 418.7/926.4 GB disk)

OS                  macOS-15.3.2-arm64-arm-64bit
Environment         Darwin
Python              3.11.11
Install             pip
Path                /Users/otto/miniconda3/envs/coral/lib/python3.11/site-packages/ultralytics
RAM                 64.00 GB
Disk                418.7/926.4 GB
CPU                 Apple M4 Pro
CPU count           12
GPU                 None
GPU count           None
CUDA                None

numpy               ✅ 1.26.4<=2.1.1,>=1.23.0
matplotlib          ✅ 3.10.1>=3.3.0
opencv-python       ✅ 4.11.0.86>=4.6.0
pillow              ✅ 11.1.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.15.2>=1.4.1
torch               ✅ 2.6.0>=1.8.0
torch               ✅ 2.6.0!=2.4.0,>=1.8.0; sys_platform == "win32"
torchvision         ✅ 0.21.0>=0.9.0
tqdm                ✅ 4.67.1>=4.64.0
psutil              ✅ 7.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.14>=2.0.0

**Comment by glenn-jocher** [comment]
Thank you for following up. We've identified the root cause in our MPS memory handling and are working on a fix. For immediate resolution, please explicitly set `device='cpu'` in your training arguments. We'll update this thread once a patch is released. Your detailed reports are invaluable in improving YOLO for the community!

**Comment by HerbOtto** [comment]
I responded on the PR page. Things are working fine with v90. Turns out i needed to close/reopen my terminal window for the new build.  

Thanks!

**Comment by glenn-jocher** [comment]
Great to hear it's resolved now! Thanks for confirming the fix and your patience as we addressed this. Your proactive testing helps improve YOLO for everyone. 🚀
