### ISSUE TITLE
confidence score

### ISSUE THREAD

**Issue by Alphacode14052004** [ultralytics/ultralytics#3046]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

while doing prediction using custom data i want to hide the confidence value but the image always pops up with the confidence value even though i used both show_conf and hide_conf 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@Alphacode14052004 👋 hi, thanks for letting us know about this possible problem with YOLO 🚀. Everything works correctly for me:

```bash
yolo predict show_conf=False show
```
![zidane](https://github.com/ultralytics/ultralytics/assets/26833433/2fa7774e-f5a7-4c57-9934-95dc6b820b9b)

We've created a few short guidelines below to help users provide what we need in order to start investigating a possible problem.

## How to create a Minimal, Reproducible Example

When asking a question, people will be better able to provide help if you provide **code** that they can easily understand and use to **reproduce** the problem. This is referred to by community members as creating a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Your code that reproduces the problem should be:

- ✅ **Minimal** – Use as little code as possible to produce the problem
- ✅ **Complete** – Provide all parts someone else needs to reproduce the problem
- ✅ **Reproducible** – Test the code you're about to provide to make sure it reproduces the problem

For [Ultralytics](https://ultralytics.com/) to provide assistance your code should also be:

- ✅ **Current** – Verify that your code is up-to-date with GitHub with `git pull` or `pip install -U ultralytics` to ensure your problem has not already been solved in the latest code version.
- ✅ **Unmodified** – Your problem must be reproducible using official Ultrlaytics code without changes. [Ultralytics](https://ultralytics.com/) does not provide support for custom code ⚠️.

If you believe your problem meets all the above criteria, please close this issue and raise a new one using the 🐛 **Bug Report** [template](https://github.com/ultralytics/ultralytics/issues/new/choose) with a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us better understand and diagnose your problem. 

Thank you! 😃

**Comment by Midii-11** [comment]
@glenn-jocher @Alphacode14052004 
I have successfully replicated the issue reported by @Alphacode14052004. After testing, I identified two scenarios

- Scenario 1: 
**Using Yolo from an IDE** (PyCharm in my case)
In this scenario, the bounding boxes are correctly drawn, but the labels and confidence scores cannot be hidden. I trained a nano YoloV8 model on a custom dataset and ran the predictions using the following code snippet:
`results = model.predict(source=all_img, imgsz=[640, 640], show_labels=True, show_conf=False)`
![image](https://github.com/ultralytics/ultralytics/assets/51723115/8f46daed-dadd-452d-aa4a-6f3957c93cda)
Even when setting `show_labels=False`, the labels remain visible. I also tried adding `augment=False` as suggested in this GitHub issue (https://github.com/ultralytics/ultralytics/issues/2046), but it did not resolve the problem.

- Scenario 2: 
**Using Yolo from the CLI**
In this scenario, I used the following commands to predict without showing labels and confidence scores:
`yolo predict model=...\runs\detect\yolov8n\weights\best.pt source=image.png imgsz=640 show_labels=False`
![image](https://github.com/ultralytics/ultralytics/assets/51723115/8a5d4c8a-b3fa-4a1a-8bed-45efc85b0a0a)
`yolo predict model=...\runs\detect\yolov8n\weights\best.pt source=image.png imgsz=640 show_conf=False`
![image](https://github.com/ultralytics/ultralytics/assets/51723115/711f612f-8f40-4d9a-b5b8-f76cbe159222)


My setup is using Ultralytics version ultralytics-8.0.115.

**Comment by glenn-jocher** [comment]
Hello @Midii-11 and thank you for bringing this issue to our attention. I have replicated the issue in two different scenarios using an IDE (PyCharm) and the CLI. When running the prediction from PyCharm, the labels and confidence scores cannot be hidden, but when running from the CLI, both can be hidden by using the `show_labels` and `show_conf` options. Using `augment=False` has also been tested without success. This issue seems to affect our YOLOv8 repo and we appreciate your patience while we investigate further.

**Comment by Alphacode14052004** [comment]
> Hello @Midii-11 and thank you for bringing this issue to our attention. I have replicated the issue in two different scenarios using an IDE (PyCharm) and the CLI. When running the prediction from PyCharm, the labels and confidence scores cannot be hidden, but when running from the CLI, both can be hidden by using the `show_labels` and `show_conf` options. Using `augment=False` has also been tested without success. This issue seems to affect our YOLOv8 repo and we appreciate your patience while we investigate further.

hello thanks for fixing it

**Comment by Alphacode14052004** [comment]
> @glenn-jocher @Alphacode14052004 I have successfully replicated the issue reported by @Alphacode14052004. After testing, I identified two scenarios
> 
> * Scenario 1:
>   **Using Yolo from an IDE** (PyCharm in my case)
>   In this scenario, the bounding boxes are correctly drawn, but the labels and confidence scores cannot be hidden. I trained a nano YoloV8 model on a custom dataset and ran the predictions using the following code snippet:
>   `results = model.predict(source=all_img, imgsz=[640, 640], show_labels=True, show_conf=False)`
>   ![image](https://user-images.githubusercontent.com/51723115/244895471-8f46daed-dadd-452d-aa4a-6f3957c93cda.png)
>   Even when setting `show_labels=False`, the labels remain visible. I also tried adding `augment=False` as suggested in this GitHub issue ([How to not display labels and conf ? #2046](https://github.com/ultralytics/ultralytics/issues/2046)), but it did not resolve the problem.
> * Scenario 2:
>   **Using Yolo from the CLI**
>   In this scenario, I used the following commands to predict without showing labels and confidence scores:
>   `yolo predict model=...\runs\detect\yolov8n\weights\best.pt source=image.png imgsz=640 show_labels=False`
>   ![image](https://user-images.githubusercontent.com/51723115/244896090-8a5d4c8a-b3fa-4a1a-8bed-45efc85b0a0a.png)
>   `yolo predict model=...\runs\detect\yolov8n\weights\best.pt source=image.png imgsz=640 show_conf=False`
>   ![image](https://user-images.githubusercontent.com/51723115/244896101-711f612f-8f40-4d9a-b5b8-f76cbe159222.png)
> 
> My setup is using Ultralytics version ultralytics-8.0.115.

thanks i also had same issues in the scenario

**Comment by glenn-jocher** [comment]
@Alphacode14052004 thank you for bringing this issue to our attention. We have identified two scenarios where the labels and confidence scores cannot be hidden in YOLOv8:

1. Using YOLO from an IDE such as PyCharm: In this scenario, the bounding boxes are correctly drawn, but the labels and confidence scores remain visible even when using `show_labels=False`. We appreciate you trying the `augment=False` option, but it did not resolve the problem.

2. Using YOLO from the CLI: In this scenario, the issue can be resolved by using the `show_labels=False` and `show_conf=False` options when running the predictions.

We would like to apologize for any inconvenience caused by this issue and assure you that we are actively investigating and working towards a resolution. Thank you for your patience and understanding.

**Comment by leosv123** [comment]
this issue not yet solved

**Comment by glenn-jocher** [comment]
Hello @leosv123, I apologize for the inconvenience that this issue has been causing you. I assure you that our team is actively working on resolving it. We appreciate your patience and understanding while we look into this matter. We are committed to making YOLOv8 the best it can be and user feedback such as yours is invaluable to us. We will update you on our progress as soon as we can. Thank you for your continued support and patience.

**Comment by sasyed3** [comment]
For yolov8, I simply did the following while running predictions:
hide_conf = True
hide_labels = True 


It hid the class number and confidence score on the bounding box.  And all I got were plain red detection boxes

**Comment by glenn-jocher** [comment]
@sasyed3 hello, thank you for sharing your successful approach of setting the `hide_conf` and `hide_labels` parameters to `True` when running YOLOv8 predictions. This indeed should result in displaying only the detection boxes, without the class labels and confidence score. If this behavior meets your requirement, it seems you have found a suitable solution. However, if you have any additional questions or concerns please don't hesitate to let us know. We appreciate your contribution to improving the use of YOLOv8.

**Comment by leosv123** [comment]
Anyway for now i have fixed it by drawing my own bounding boxed using matplotlib.patches but the function in yolov8 does not work

**Comment by glenn-jocher** [comment]
@leosv123 hello! Thank you for your patience and for finding a workaround in the meantime while resolving this issue. It seems there could be a possible discrepancy in the behavior of the `hide_conf` and `hide_labels` attributes and their interpreted counterparts `show_conf` and `show_labels`. We apologize for the inconvenience. 

Please note that usage of 'hide_conf' and 'hide_labels' is officially deprecated. Instead, they are replaced by 'show_conf' and 'show_labels'. However, if setting both these latter parameters to False is not able to hide the labels and confidence scores in your situation, then this is something we will need to look into and rectify. 

We welcome your feedback and value your input as it helps us to improve YOLOv8. We're committed to ensuring it meets the needs of our users. Thank you for your understanding and for bringing this problem to our attention!

**Comment by aramirr** [comment]
Hi @glenn-jocher,
Is there a fix for this issue? This is still reproducible. Thanks!

**Comment by UltralyticsAssistant** [comment]
@aramirr confidence scores can be hidden like this:

```
yolo predict show show_conf=False
```

![zidane](https://github.com/user-attachments/assets/f9d5b12b-272f-4963-acce-161da3737591)
