### ISSUE TITLE
TypeError when setting "mosaic" augmentation to any value != 1

### ISSUE THREAD

**Issue by Robotatron** [ultralytics/ultralytics#515]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Bug

Mosaic = 1 (default) the training works. Setting mosaic to 0.5 or 0.66 or 0 aborts the run with an error. Setting mosaic in the same config back to 1 let's me train. 

```
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to YOLOv8/Sagemaker/08-X-640-<scratch><mosaic=0.5>
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/3358 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/opt/conda/envs/oneformer/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/cli.py", line 148, in entrypoint
    cli(cfg)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/cli.py", line 84, in cli
    func(cfg)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/v8/segment/train.py", line 153, in train
    model.train(**cfg)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 203, in train
    self.trainer.train()
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 185, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/engine/trainer.py", line 285, in _do_train
    for i, batch in pbar:
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/opt/conda/envs/oneformer/lib/python3.8/site-packages/ultralytics/yolo/data/dataset.py", line 173, in collate_fn
    value = torch.stack(value, 0)
TypeError: expected Tensor as element 1 in argument 0, but got str
```

### Environment

Ultralytics YOLOv8.0.11 🚀 Python-3.8.15 torch-1.10.1 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Robotatron** [comment]
Reproducible with `yolo train segment mosaic=0.5`

**Comment by glenn-jocher** [comment]
@Robotatron thanks for the reproduce code, I can reproduce. Will take a look.

**Comment by glenn-jocher** [comment]
@Laughing-q @AyushExel it seems we have a bug in v8 loader when mosaic is not equal to 1.0 where the image is not being letterboxed.

**Comment by glenn-jocher** [comment]
@Robotatron should be resolved in #699 scheduled for 8.0.24 later today.

**Comment by flo-crn** [comment]
Hi, I still have an error when trying to set "mosaic=0.0" on my yolov8-seg training (i'm using the 8.0.54 ultralytics version).
Here are the code I used and the error raised :

`yolo task=segment mode=train model=yolov8s-seg.pt data=data.yaml epochs=3  imgsz=1280 batch=20 mosaic=0.0`

`Image sizes 1280 train, 1280 val
Using 8 dataloader workers
Logging results to runs/segment/train42
Starting training for 3 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/189 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "/home/floriane/miniconda3/envs/yolo-track/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/floriane/miniconda3/envs/yolo-track/lib/python3.9/site-packages/ultralytics/yolo/cfg/__init__.py", line 249, in entrypoint
    getattr(model, mode)(verbose=True, **overrides)
  File "/home/floriane/miniconda3/envs/yolo-track/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 207, in train
    self.trainer.train()
  File "/home/floriane/miniconda3/envs/yolo-track/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 183, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/home/floriane/miniconda3/envs/yolo-track/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 301, in _do_train
    preds = self.model(batch["img"])
  File "/home/floriane/miniconda3/envs/yolo-track/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/floriane/miniconda3/envs/yolo-track/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 194, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/floriane/miniconda3/envs/yolo-track/lib/python3.9/site-packages/ultralytics/nn/tasks.py", line 57, in _forward_once
    x = m(x)  # run
  File "/home/floriane/miniconda3/envs/yolo-track/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/floriane/miniconda3/envs/yolo-track/lib/python3.9/site-packages/ultralytics/nn/modules.py", line 348, in forward
    return torch.cat(x, self.d)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 46 but got size 45 for tensor number 1 in the list.
`
Is anyone else still having this error ?

Thank you

**Comment by Laughing-q** [comment]
@flo-crn it works fine to me with coco128-seg.yaml
```bash
yolo task=segment mode=train model=yolov8s-seg.pt data=coco128-seg.yaml epochs=3  imgsz=1280 batch=4 mosaic=0.0
```
![image](https://user-images.githubusercontent.com/61612323/225874838-99ee047b-6762-4a77-b5d5-eb48322d061a.png)
