### ISSUE TITLE
unable to load dataset in latest version

### ISSUE THREAD

**Issue by garyfoohw** [ultralytics/ultralytics#873]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Problem appears on versions >=8.0.30.
Problem does not appear if use <=8.0.29.

`model.train` is having error detecting training `data.yaml` file which exists.

Screenshot below from run using ultralytics 8.0.31
![image](https://user-images.githubusercontent.com/86142858/217608361-dfceb252-2d15-43ae-a734-c3e7a5bebf1b.png)

### Environment

- YOLO: Ultralytics YOLOv8.0.31 🚀 Python-3.8.10 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15110MiB)
- OS: Google CoLab
- Python: 3.8.10

### Minimal Reproducible Example

```
model.train(task='segment',data=os.path.join(dataset.location,"data.yaml"),epochs=100,imgsz=640)
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@garyfoohw your dataset is incorrectly configured. Your data yaml is found correctly, it contains incorrect paths as indicated in the error message.

**Comment by garyfoohw** [comment]
@glenn-jocher 
`data.yaml` seems fine to me. 
It is pulled direct from roboflow, and runs fine with ultralytics <=8.0.29.
I don't understand why the same file will break in another version of ultralytics.
```
names:
- ULD
nc: 1
roboflow:
  license: Private
  project: uld_instance_seg
  url: https://app.roboflow.com/abcdefg/uld_instance_seg/6
  version: 6
  workspace: abcdefg
test: ../test/images
train: ULD_instance_seg-6/train/images
val: ULD_instance_seg-6/valid/images
```

**Comment by 25benjaminli** [comment]
I moved my data.yaml file into the root directory of the folder in an attempt to try solve this issue. I was able to get training working. For context, the command that I used to train is listed below:

`yolo detect train model=[PATH TO WEIGHTS] data=data.yaml epochs=40 batch=32`

HOWEVER, I do not think this solution is valid, because validation and testing is a completely different story. 

When I run,
`yolo detect val model=[BEST WEIGHTS PATH] data=data.yaml`

I get a similar error to that of the OP. 

`Dataset 'data.yaml' not found ⚠️, missing paths ['/content/datasets/[DATASET_NAME]/valid/images']`

My data.yaml paths are attached below. 
`test: ../test/images
train: Bacteria-27/train/images
val: Bacteria-27/valid/images`

I think this situation could be made easier if I could simply run yolov8 from the cloned git repository rather than using the CLI or python, so how would I do that?

**Comment by glenn-jocher** [comment]
@25benjaminli thanks for the info! You can always git clone instead of pip installing. The Colab notebook has one cell for each install, i.e.:
https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb

<img width="746" alt="Screenshot 2023-02-09 at 10 49 53" src="https://user-images.githubusercontent.com/26833433/217738742-76b81724-c04d-46b4-a650-e8570685c5bb.png">

**Comment by 25benjaminli** [comment]
I found that if you write everything as an absolute path from the root directory in colab, it seems to work fine. 
`!yolo detect val model=/content/drive/MyDrive/yolov8/runs/detect/train21/weights/best.pt data=/content/drive/MyDrive/yolov8/data.yaml`

Try something along these lines.

**Comment by paraiko** [comment]
I can conform this issue as well for a classification training task.
I've tried both absolute and relative paths in the dataset.yaml file.

Nothing works with versions >8.0.29, but the exact same .yaml file works fine with <= 8.0.29
``
Somehow it tries to download the .yaml file from github and actually places an empty .yaml.zip file in the correct path.

![Screenshot from 2023-02-10 20-35-11](https://user-images.githubusercontent.com/1861138/218183432-2083b1c6-7385-4388-bbe1-974d6c2a5689.png)

**Comment by SkalskiP** [comment]
Hi, @glenn-jocher 👋🏻! Any chance of working on this issue? I just checked and got:

```
Ultralytics YOLOv8.0.35 🚀 Python-3.8.10 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15110MiB)
yolo/engine/trainer: task=segment, mode=train, model=yolov8s-seg.pt, data=/content/datasets/R2P2-2/data.yaml, epochs=1, patience=50, batch=16, imgsz=640, save=True, save_period=-1, cache=False, device=None, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, min_memory=False, overlap_mask=True, mask_ratio=4, dropout=False, val=True, split=val, save_json=False, save_hybrid=False, conf=0.001, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=ultralytics/assets/, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=17, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.001, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.6, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, save_dir=runs/segment/train
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/trainer.py", line 124, in __init__
    self.data = check_det_dataset(self.args.data)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/data/utils.py", line 240, in check_det_dataset
    raise FileNotFoundError(msg)
FileNotFoundError: 
Dataset '/content/datasets/R2P2-2/data.yaml' not found ⚠️, missing paths ['/content/datasets/R2P2-2/R2P2-2/valid/images']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/cfg/__init__.py", line 304, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/model.py", line 220, in train
    self.trainer = self.TrainerClass(overrides=overrides)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/v8/segment/train.py", line 24, in __init__
    super().__init__(cfg, overrides)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/trainer.py", line 128, in __init__
    raise FileNotFoundError(emojis(f"Dataset '{self.args.data}' error ❌ {e}")) from e
FileNotFoundError: Dataset '/content/datasets/R2P2-2/data.yaml' error ❌ 
Dataset '/content/datasets/R2P2-2/data.yaml' not found ⚠️, missing paths ['/content/datasets/R2P2-2/R2P2-2/valid/images']
```

This is my `data.yaml`:

```
names:
- Oil
- jam
- pasta
- rice
- soda
- tomato sauce
nc: 6
roboflow:
  license: Public Domain
  project: r2p2
  url: https://universe.roboflow.com/new-workspace-crr3c/r2p2/dataset/2
  version: 2
  workspace: new-workspace-crr3c
test: ../test/images
train: R2P2-2/train/images
val: R2P2-2/valid/images
```

And this is my file tree:

![Screenshot 2023-02-12 at 22 21 33](https://user-images.githubusercontent.com/26109316/218337932-83d80b61-8d31-4a50-98ae-29ce76e5fee2.png)

It looks like `/content/datasets/R2P2-2/R2P2-2/valid/images` exists, and the dataset is configured properly.

**Comment by yeldarby** [comment]
This should be fixed in datasets downloaded with the latest version of `roboflow`. We’re now dynamically rewriting the yaml paths to the new format when `ultralytics>=0.30.0` is detected.

**Comment by SkalskiP** [comment]
@garyfoohw, @25benjaminli, and @paraiko do you still experience issues? Would be great if you could test, but make sure you use the latest `roboflow` to download the dataset.

**Comment by paraiko** [comment]
I have tested (ultralytics package version 8.0.40). Unfortunately, this did not solve my issue.

However, I tested a bit more and found that if I train a task=detect model on the dataset downloaded from roboflow it does work correctly.

If I try to train a classify only model (what I intend to do), then it gives me the same error as in the screenshot above, both for the roboflow dataset and for my own dataset (which has pictures separated in folders for labels and not a yolo style .txt labels for each image) 

I am starting to wonder if the problem is specific for classification only (did not test segmentation only) workloads.

**Comment by SkalskiP** [comment]
@paraiko version of `ultralytics` shouldn't matter anymore. The only things that matter are the version of `roboflow` and the order of operations.

1. Install `ultralytics` and `roboflow>=0.2.31`.
2. Download dataset using `roboflow`
3. Train model

If I understood your comment correctly. You manage to train object detection but not image classification?

**Comment by paraiko** [comment]
That's correct, I can train detection and not classification.

I never had the roboflow package installed, but when I find time tomorrow I will try and see if that works.

Btw version of ultralytics did matter. When I switched back to 8.0.29 I had to manually adjust the paths in the data.yaml file. To make it work again, I had to edit in the dataset name in the path.

**Comment by mr-lovalova** [comment]
Hello @glenn-jocher, thanks for a nice project! I think this is caused by the project expecting the data to be in the a folder called "dataset". So a quick fix is to put your dataset in a folder called dataset and not provide "dataset" in the yaml path. Otherwise will be dataset/dataset.

![Skærmbillede 2023-03-08 kl  13 55 37](https://user-images.githubusercontent.com/47424670/223726542-c3a650c0-8e2d-40c9-81e4-1e06f328a012.png)

**Comment by mr-lovalova** [comment]
> Hello @glenn-jocher, thanks for a nice project! I think this is caused by the project expecting the data to be in the a folder called "dataset". So a quick fix is to put your dataset in a folder called dataset and not provide "dataset" in the yaml path. Otherwise will be dataset/dataset.
> 
> ![Skærmbillede 2023-03-08 kl 13 55 37](https://user-images.githubusercontent.com/47424670/223726542-c3a650c0-8e2d-40c9-81e4-1e06f328a012.png)

JUST TO CLARIFY: These classes have to do with the colors and format of specific label types used in electrical cabinets not human profiling.

**Comment by erkara** [comment]
> > Hello @glenn-jocher, thanks for a nice project! I think this is caused by the project expecting the data to be in the a folder called "dataset". So a quick fix is to put your dataset in a folder called dataset and not provide "dataset" in the yaml path. Otherwise will be dataset/dataset.
> > ![Skærmbillede 2023-03-08 kl 13 55 37](https://user-images.githubusercontent.com/47424670/223726542-c3a650c0-8e2d-40c9-81e4-1e06f328a012.png)
> 
> JUST TO CLARIFY: These classes have to do with the colors and format of specific label types used in electrical cabinets not human profiling.

I think this is the major cause. Here is what I did, 
(1) I put my train,valid folders in "datasets" folder
(2) My yaml file looks like
path: ./    
train: train/images  
val: valid/images 
(3) Then usual command model.train(data='custom.yml', epochs=5, task='detect')

Now the strange thing is that it trains but does not validate



Transferred 319/355 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
optimizer: SGD(lr=0.01) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias
train: Scanning /home/erkara/Dropbox/Teaching/Intro2DeepLearning/projects/face-detection/datasets/train/labels.cache... 127 images, 0 backgrounds, 0 corrupt: 100%|██████████| 127/127 [00:00<?, ?it/s]
val: Scanning /home/erkara/Dropbox/Teaching/Intro2DeepLearning/projects/face-detection/datasets/valid/labels.cache... 36 images, 0 backgrounds, 0 corrupt: 100%|██████████| 36/36 [00:00<?, ?it/s]
Plotting labels to runs/detect/train23/labels.jpg... 
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/detect/train23
Starting training for 1 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/1      2.31G      2.583      5.759      1.067         64        640: 100%|██████████| 8/8 [00:01<00:00,  4.06it/s]
/home/erkara/anaconda3/envs/face/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:139: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  3.13it/s]
                   all         36        108          0          0          0          0

1 epochs completed in 0.001 hours.
Optimizer stripped from runs/detect/train23/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train23/weights/best.pt, 6.2MB

Validating runs/detect/train23/weights/best.pt...
Ultralytics YOLOv8.0.74 🚀 Python-3.11.2 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce RTX 2070 Super, 7982MiB)
YOLOv8n summary (fused): 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs
Traceback (most recent call last):
  File "/home/erkara/Dropbox/Teaching/Intro2DeepLearning/projects/face-detection/draft.py", line 9, in <module>
    model.train(data='three_droplet.yml', epochs=1)
  File "/home/erkara/anaconda3/envs/face/lib/python3.11/site-packages/ultralytics/yolo/engine/model.py", line 367, in train
    self.trainer.train()
  File "/home/erkara/anaconda3/envs/face/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/home/erkara/anaconda3/envs/face/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 387, in _do_train
    self.final_eval()
  File "/home/erkara/anaconda3/envs/face/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 523, in final_eval
    self.metrics = self.validator(model=f)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/erkara/anaconda3/envs/face/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/erkara/anaconda3/envs/face/lib/python3.11/site-packages/ultralytics/yolo/engine/validator.py", line 129, in __call__
    raise FileNotFoundError(emojis(f"Dataset '{self.args.data}' for task={self.args.task} not found ❌"))
FileNotFoundError: Dataset 'custom.yml' for task=detect not found ❌

Process finished with exit code 1

**Comment by jmmarotta** [comment]
In reference to the issue above, I believe this is because you're using `.yml` instead of `.yaml`.

```
FileNotFoundError: Dataset '/content/drive/MyDrive/datasets/detecting-dataset/data.yml' for task=detect not found ❌
```

In **ultralytics/yolo/engine/validator.py** there is an issue with the conditional on line 124.
```
if isinstance(self.args.data, str) and self.args.data.endswith('.yaml'):
  self.data = check_det_dataset(self.args.data)
elif self.args.task == 'classify':
  self.data = check_cls_dataset(self.args.data)
else:
  raise FileNotFoundError(emojis(f"Dataset '{self.args.data}' for task={self.args.task} not found ❌"))
```

Maybe it should be changed to:
```
if isinstance(self.args.data, str) and self.args.data.endswith(('.yaml', '.yml')):
```

For now if you're having an issue with this, make sure that your extension is `.yaml` and not `.yml`.

**Comment by erkara** [comment]
> In reference to the issue above, I believe this is because you're using `.yml` instead of `.yaml`.
> 
> I received the following error:
> 
> ```
> FileNotFoundError: Dataset '/content/drive/MyDrive/datasets/detecting-dataset/data.yml' for task=detect not found ❌
> ```
> 
> In **ultralytics/yolo/engine/validator.py** the conditional on line 124 only checks for the `.yaml` ending not `.yml`.
> 
> ```
> if isinstance(self.args.data, str) and self.args.data.endswith('.yaml'):
>   self.data = check_det_dataset(self.args.data)
> elif self.args.task == 'classify':
>   self.data = check_cls_dataset(self.args.data)
> else:
>   raise FileNotFoundError(emojis(f"Dataset '{self.args.data}' for task={self.args.task} not found ❌"))
> ```
> 
> Maybe it should be changed to:
> 
> ```
> if isinstance(self.args.data, str) and self.args.data.endswith(('.yaml', '.yml')):
> ```
> 
> For now, if you're having an issue with this, make sure that your extension is `.yaml` and not `.yml`.

Amazing catch!! This solved the issue, thank you so much @jmmarotta

**Comment by glenn-jocher** [comment]
Thank you for reporting this issue @erkara. We are aware of the problem and appreciate the time you took to investigate it. 

Indeed, the `.yml` extension is not being accepted at the moment, but it could be possible to add support for it to validate it as a valid file extension. 

In the meantime, please make sure that your configuration file extension is `.yaml` instead of `.yml`.  

Thank you again for taking the time to report this issue, and let us know if you have any more questions or concerns.

**Comment by erkara** [comment]
I wonder if anyone addressed the problem above about 

> > > Hello @glenn-jocher, thanks for a nice project! I think this is caused by the project expecting the data to be in the a folder called "dataset". So a quick fix is to put your dataset in a folder called dataset and not provide "dataset" in the yaml path. Otherwise will be dataset/dataset.
> > > ![Skærmbillede 2023-03-08 kl 13 55 37](https://user-images.githubusercontent.com/47424670/223726542-c3a650c0-8e2d-40c9-81e4-1e06f328a012.png)
> > 
> > 
> > JUST TO CLARIFY: These classes have to do with the colors and format of specific label types used in electrical cabinets not human profiling.
> 
> I think this is the major cause. Here is what I did, (1) I put my train,valid folders in "datasets" folder (2) My yaml file looks like path: ./ train: train/images val: valid/images (3) Then usual command model.train(data='custom.yml', epochs=5, task='detect')
> 
> Now the strange thing is that it trains but does not validate
> 
> ====usual stuff before this loading model etc
> 
> Transferred 319/355 items from pretrained weights AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n... AMP: checks passed white_check_mark optimizer: SGD(lr=0.01) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias train: Scanning /home/erkara/Dropbox/Teaching/Intro2DeepLearning/projects/face-detection/datasets/train/labels.cache... 127 images, 0 backgrounds, 0 corrupt: 100%|██████████| 127/127 [00:00<?, ?it/s] val: Scanning /home/erkara/Dropbox/Teaching/Intro2DeepLearning/projects/face-detection/datasets/valid/labels.cache... 36 images, 0 backgrounds, 0 corrupt: 100%|██████████| 36/36 [00:00<?, ?it/s] Plotting labels to runs/detect/train23/labels.jpg... Image sizes 640 train, 640 val Using 8 dataloader workers Logging results to runs/detect/train23 Starting training for 1 epochs...
> 
> ```
>   Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
>     1/1      2.31G      2.583      5.759      1.067         64        640: 100%|██████████| 8/8 [00:01<00:00,  4.06it/s]
> ```
> 
> /home/erkara/anaconda3/envs/face/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:139: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`. Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. " Class Images Instances Box(P R mAP50 mAP50-95): 100%|██████████| 2/2 [00:00<00:00, 3.13it/s] all 36 108 0 0 0 0
> 
> 1 epochs completed in 0.001 hours. Optimizer stripped from runs/detect/train23/weights/last.pt, 6.2MB Optimizer stripped from runs/detect/train23/weights/best.pt, 6.2MB
> 
> Validating runs/detect/train23/weights/best.pt... Ultralytics YOLOv8.0.74 rocket Python-3.11.2 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce RTX 2070 Super, 7982MiB) YOLOv8n summary (fused): 168 layers, 3005843 parameters, 0 gradients, 8.1 GFLOPs Traceback (most recent call last): File "/home/erkara/Dropbox/Teaching/Intro2DeepLearning/projects/face-detection/draft.py", line 9, in model.train(data='three_droplet.yml', epochs=1) File "/home/erkara/anaconda3/envs/face/lib/python3.11/site-packages/ultralytics/yolo/engine/model.py", line 367, in train self.trainer.train() File "/home/erkara/anaconda3/envs/face/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 190, in train self._do_train(world_size) File "/home/erkara/anaconda3/envs/face/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 387, in _do_train self.final_eval() File "/home/erkara/anaconda3/envs/face/lib/python3.11/site-packages/ultralytics/yolo/engine/trainer.py", line 523, in final_eval self.metrics = self.validator(model=f) ^^^^^^^^^^^^^^^^^^^^^^^ File "/home/erkara/anaconda3/envs/face/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/home/erkara/anaconda3/envs/face/lib/python3.11/site-packages/ultralytics/yolo/engine/validator.py", line 129, in **call** raise FileNotFoundError(emojis(f"Dataset '{self.args.data}' for task={self.args.task} not found x")) FileNotFoundError: Dataset 'custom.yml' for task=detect not found x
> 
> Process finished with exit code 1

I wonder if anyone addressed this issue. It looks like it's caused by 
/ultralytics/yolo/utils/__init__.py around line 503 where the dataset_dir is set as

'datasets_dir': str(datasets_root / 'datasets'),  # default datasets directory.

I removed ''datasets'' but did not fix the problem, maybe overwritten somewhere else. Thanks for the help!

**Comment by glenn-jocher** [comment]
@erkara hello, 

Thank you for bringing this issue to our attention. 

It seems like there is an issue with providing the correct path to the dataset in the `.yaml` file. Specifically, does the path include the folder name `dataset` or not? 

One user suggested that it's necessary to put the dataset in a folder called `dataset` and not provide `dataset` in the path in the `.yaml` file. Another user suggested that the issue might be located in `/ultralytics/yolo/utils/__init__.py` around line 503 since the `datasets_dir` is set to include `datasets`. 

It's possible that this could be causing the problem, but it would require further investigation to be sure. In general, please make sure to provide the correct path to your dataset in the `.yaml` file to avoid any issues. 

Please let us know if you have further questions or concerns.

**Comment by erkara** [comment]
(1) I am in a folder called "tutorial" and keep the dataset inside "tutorial/datasets/" where I have train-valid-test folders as well as sample.yaml. Here is what's inside yaml;
  path: datasets/
  train: train/images  
  val: valid/images  
  test: test/images 
  nc: 1  
  names: ['droplet'] 

Unless we keep those train-valid-test folders inside a folder called "datasets",  model.train always gives the data not found error described above. For example, when I change the name of "datasets" folder to something else and modify yaml file accordingly, I get the same error. 

This error is kind of problematic because I used to keep all of datasets in a single root folder  somersetting like 
_data_dir/experiment1/train-valid-test data_dir/experiment2/train-valid-test etc._ 
in YOLOv5 and work with them flawlessly. Now I cannot. Maybe I am missing something, but it would be great to have a resolution. Thank you for taking time to look at the issue @glenn-jocher

**Comment by rromanchuk** [comment]
Using `data=coco128.yaml` across all documentation is really detrimental to anyone getting started. I've got a magic relative yaml file that includes a path param with a relative path to a root dataset, another config value `datasets_dir` from `yolo settings`, 

My magic `coco128.yaml` string i guess is really 

`yolo train data="/opt/homebrew/lib/python3.11/site-packages/ultralytics/datasets/coco128.yaml" model=yolov8n.pt epochs=10 lr0=0.01 device=mps`

```yaml
# parent
# ├── ultralytics
# └── datasets
#     └── coco128  ← downloads here (7 MB)

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../datasets/coco128  # dataset root dir
train: images/train2017  # train images (relative to 'path') 128 images
val: images/train2017  # val images (relative to 'path') 128 images
test:  # test images (optional)
```

If i try to exactly recreate 

`FileNotFoundError: Dataset '/My/Absolute/Path/To/datasets/my_data/my_data.yml' for task=detect not found ❌`

`project` and `name` params seems 

Is there an example sans internet connection? So no roboflow and no auto fetching labels and images laid out how the software expects. Eg 10 images and 10 labels with absolute file paths in arbitrary locations, 1 model, relative to nothing?

**Comment by rromanchuk** [comment]
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/engine/validator.py#L126

woof, fragile

**Comment by glenn-jocher** [comment]
@rromanchuk hello and thank you for bringing this issue to our attention!

We understand that you are encountering a problem with the `ultralytics/yolo/engine/validator.py` file in the YOLOv8 repository. Specifically, you mentioned that the `args.validator` function does a string comparison on the `data=` parameter with a regex pattern, and it aborts if the parameter does not match the pattern `/\.yaml$/`.

We appreciate your feedback about the fragility of this particular section of code. We apologize for any inconvenience it may have caused. We are constantly working to improve the stability and usability of our codebase.

In order to better assist you with this issue, could you please provide more details about the specific problem you are encountering and any error messages you are receiving? This will help us to better understand the root cause of the issue and provide you with an appropriate solution.

Thank you again for reaching out to us, and we look forward to assisting you further with this matter.

**Comment by glenn-jocher** [comment]
@rromanchuk thank you for your feedback and detailed explanation of the issues you are facing.

We understand that you encountered some challenges with the `.yml` extension and went down the wrong path as a result. We apologize for the confusion caused.

Regarding your goal of programmatically supplying train/val/test data with explicit `.txt` files that don't rely on relative directory structures, we currently do not have specific annotation-related keys for this purpose. However, you may be able to achieve your desired configuration by providing the relevant information as siblings or through derived inputs.

We acknowledge that there are references to repo-specific assumptions, such as the YOLOv5 git clone, which may make the pipeline environment feel awkward. We appreciate your feedback on this aspect, and we will look into clarifying and filling in any gaps in the documentation to better support programmatic custom datasets without relying on services like Roboflow.

We encourage you to delve further into the codebase and consider potential elegant solutions for your use case. If you come across any insights or improvements, please feel free to share them with us. Your contributions can greatly enhance the overall experience for users in similar situations.

Thank you again for bringing these issues to our attention, and we value your efforts to help us improve.

**Comment by glenn-jocher** [comment]
@promaprogga it looks like you've run into a CUDA device-side assert error while training a YOLOv8 model using a pretrained `best.pt` file you downloaded from a Hugging Face repository. This specific type of error (`device-side assert triggered`) usually occurs when there is a mismatch or an out-of-bound issue with the indices in CUDA operations, which can't be easily interpreted without more context.

Here are a few steps you might want to take to diagnose and potentially fix the problem:

1. **Check PyTorch and CUDA versions**: Ensure that the versions of PyTorch and CUDA installed in your environment are compatible with each other and with YOLOv8.

2. **Inspect the Dataset**: Verify that your `data.yaml` is correctly set up and that the label indices in your dataset are within the expected range. For instance, if your model is configured for a certain number of classes, make sure that all class indices in your label data are within that range.

3. **Set `CUDA_LAUNCH_BLOCKING=1`**: As suggested in the error message, you might want to rerun your code with `CUDA_LAUNCH_BLOCKING=1` environment variable set to get more insightful traceback information that is synchronized with the location of the actual issue.

4. **Check for Mixed Precision Training Issues**: If you're using mixed precision (AMP), there might be an issue related to this. Although the log doesn't indicate AMP was enabled, it can sometimes cause similar issues.

5. **Evaluate Custom Changes**: If you made any custom changes to the model or the training script, review those changes to ensure they are not causing the error.

For now, here's what I might suggest as next steps:

- Revisit your data preparation steps to ensure the labels are correctly formatted and bounded.
- If the issue persists, consider using `CUDA_LAUNCH_BLOCKING=1` when running your script to get a more detailed error message, which can help you or the community to pinpoint the problem.
- If you continue to face the issue, you might want to open an issue on the Ultralytics YOLOv8 repository with the detailed error logs after enabling `CUDA_LAUNCH_BLOCKING=1`.

These issues can be challenging to debug, but starting with these steps should put you on the right path to finding a solution. Thank you for your patience and detailed error reporting, as it greatly aids in troubleshooting your training process.

**Comment by cnydo** [comment]
> (1) I am in a folder called "tutorial" and keep the dataset inside "tutorial/datasets/" where I have train-valid-test folders as well as sample.yaml. Here is what's inside yaml; path: datasets/ train: train/images val: valid/images test: test/images nc: 1 names: ['droplet']
> 
> Unless we keep those train-valid-test folders inside a folder called "datasets", model.train always gives the data not found error described above. For example, when I change the name of "datasets" folder to something else and modify yaml file accordingly, I get the same error.
> 
> This error is kind of problematic because I used to keep all of datasets in a single root folder somersetting like _data_dir/experiment1/train-valid-test data_dir/experiment2/train-valid-test etc._ in YOLOv5 and work with them flawlessly. Now I cannot. Maybe I am missing something, but it would be great to have a resolution. Thank you for taking time to look at the issue @glenn-jocher

@erkara I changed the yaml file like this and it worked:
```
path: ../data
test: test/images
train: train/images
val: val/images
```
and my dataset structure:
```
data
├── train
│   ├── images
│   ├── labels
├── test
│   ├── images
│   └── labels
└── val
    ├── images
    └── labels
 ```

**Comment by glenn-jocher** [comment]
@cnydo It seems like the issue arises from the relative paths in your `data.yaml` file. To resolve the problem, ensure that the `path` key in your `data.yaml` correctly reflects the relative location of your dataset folders from where you are running `model.train`.

For example, if your dataset folders and `data.yaml` are within the "tutorial/datasets/" directory and you execute your script from the "tutorial/" directory, your `data.yaml` should look like this:

```yaml
path: datasets/
train: train/images
val: valid/images
test: test/images
nc: 1
names: ['droplet']
```

Remember to call `model.train` with the correct path to your `data.yaml`:

```python
model.train(data='datasets/data.yaml')
```

If you change any folder names or move your script's execution location, update the `path` key in the `data.yaml` accordingly to avoid the "data not found" error.

Also, the Ultralytics `settings.yaml` might override the expected paths. If you encounter persistent issues, update the settings directly:

```python
from ultralytics import settings

# Update dataset directory
settings.update({'datasets_dir': '/the/absolute/path/to/your/data/folder'})
```

Lastly, providing an absolute path to the `data` argument in `model.train()` can be another solution, bypassing any relative path ambiguities.

These suggestions should help you to have a more flexible dataset setup similar to your previous workflow with YOLOv5.

**Comment by VladimirKarzh** [comment]
can you please help to figure out what is the problem in my case:
i try to follow instructions on this page https://docs.ultralytics.com/datasets/detect/#supported-datasets
so i created following data stucture:
![image](https://github.com/ultralytics/ultralytics/assets/136513606/91987253-f4f8-49a1-b8f3-6986a2b1befc)
also on this screenshot you can see how i try to start training from python
my yaml file have following content:
![image](https://github.com/ultralytics/ultralytics/assets/136513606/67e641a8-2090-4afa-80e0-64dfbb7544c7)

unfortunately i have errors like some other participants 
eg@ubuntu:~/VSOSH24$ /usr/bin/python3 /home/eg/VSOSH24/trainYolo.py
WARNING ⚠️ Ultralytics settings reset to default values. This may be due to a possible problem with your settings or a recent ultralytics package update. 
View settings with 'yolo settings' or at '/home/eg/.config/Ultralytics/settings.yaml'
Update settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'.
Using device: cuda
engine/trainer: task=classify, mode=train, model=yolov8n-cls.pt, data=/home/eg/VSOSH24/dobble_nabor_v2/dobble_boxes.yaml, epochs=1, time=None, patience=50, batch=16, imgsz=420, save=True, save_period=-1, cache=False, device=cuda:0, workers=8, project=None, name=train36, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/classify/train36

Dataset not found ⚠️, missing path /home/eg/VSOSH24/dobble_nabor_v2/dobble_boxes.yaml, attempting download...
Downloading https://github.com/ultralytics/yolov5/releases/download/v1.0/home/eg/VSOSH24/dobble_nabor_v2/dobble_boxes.yaml.zip to '/home/eg/VSOSH24/dobble_nabor_v2/dobble_boxes.yaml.zip'...
⚠️ Download failure, retrying 1/3 https://github.com/ultralytics/yolov5/releases/download/v1.0//home/eg/VSOSH24/dobble_nabor_v2/dobble_boxes.yaml.zip...
#################################################################################################################################################################################### 100.0%
Dataset download success ✅ (7.0s), saved to /home/eg/VSOSH24/dobble_nabor_v2/dobble_boxes.yaml

Traceback (most recent call last):
  File "/home/eg/.local/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 131, in init
    self.data = check_cls_dataset(self.args.data)
  File "/home/eg/.local/lib/python3.8/site-packages/ultralytics/data/utils.py", line 396, in check_cls_dataset
    names = [x.name for x in (data_dir / "train").iterdir() if x.is_dir()]  # class names list
  File "/home/eg/.local/lib/python3.8/site-packages/ultralytics/data/utils.py", line 396, in <listcomp>
    names = [x.name for x in (data_dir / "train").iterdir() if x.is_dir()]  # class names list
  File "/usr/lib/python3.8/pathlib.py", line 1122, in iterdir
    for name in self._accessor.listdir(self):
NotADirectoryError: [Errno 20] Not a directory: '/home/eg/VSOSH24/dobble_nabor_v2/dobble_boxes.yaml/train'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eg/VSOSH24/trainYolo.py", line 15, in <module>
    model.train(data='/home/eg/VSOSH24/dobble_nabor_v2/dobble_boxes.yaml', epochs=1, imgsz=420) 
  File "/home/eg/.local/lib/python3.8/site-packages/ultralytics/engine/model.py", line 372, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
  File "/home/eg/.local/lib/python3.8/site-packages/ultralytics/models/yolo/classify/train.py", line 39, in init
    super().__init__(cfg, overrides, _callbacks)
  File "/home/eg/.local/lib/python3.8/site-packages/ultralytics/engine/trainer.py", line 137, in init
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
RuntimeError: Dataset '/home/eg/VSOSH24/dobble_nabor_v2/dobble_boxes.yaml' error ❌ [Errno 20] Not a directory: '/home/eg/VSOSH24/dobble_nabor_v2/dobble_boxes.yaml/train'

As far as i understand main problem is that Yolo do not understand yaml file and tries to download it:
Dataset not found ⚠️, missing path /home/eg/VSOSH24/dobble_nabor_v2/dobble_boxes.yaml, attempting download...

how to persuade it just to open and read file?))

if i do "cat /home/eg/VSOSH24/dobble_nabor_v2/dobble_boxes.yaml" in terminal its ok

as a results yolo tries to train folder '/home/eg/VSOSH24/dobble_nabor_v2/dobble_boxes.yaml/train'  that do not exist

Yolo version 8.1.7
